version: "3.9"

services:
  db:
    image: postgres:16
    container_name: timi-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # Volume pour persister les données
      - pgdata:/var/lib/postgresql/data
      # Scripts d'initialisation (création table chantiers)
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      # Expose si tu veux te connecter depuis un client DB local
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: timi-api
    environment:
      # L'API lit DB_URL et PORT
      DB_URL: ${DB_URL}
      PORT: ${PORT}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT}:5000"
    # En dev tu peux monter le code pour live reload si tu veux (optionnel)
    # volumes:
    #   - ./app:/usr/src/app/app
    # command: ["npm","run","dev"]   # si tu veux nodemon en conteneur

volumes:
  pgdata:
